services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - CLIENT_PORT=3000
      - SERVER_PORT=3001
      - HOSTED_URL=http://ec2-52-59-11-149.eu-central-1.compute.amazonaws.com
      - LOCAL_HOSTED_URL=http://localhost

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PUBLIC_CLIENT_PORT=3000
      - PUBLIC_SERVER_PORT=3001
      - PUBLIC_HOSTED_URL=http://ec2-52-59-11-149.eu-central-1.compute.amazonaws.com
      - PUBLIC_LOCAL_HOSTED_URL=http://localhost